feat(examples) : adding currency parameter in SPAR
factset/analyticsapi-engines-dotnet-sdk pull request #67
Opened 2022-01-10 10:02 UTC by srajak8

2022-01-10 10:49 UTC, saigiridhar21 requested changes

2022-01-10 10:49 UTC, saigiridhar21 commented on examples/FactSet.AnalyticsAPI.Engines.Example/Examples/SPAREngineMultipleUnitExample.cs
> +        private const string Frequency = "Monthly";
Can you follow the naming conventions?

2022-01-10 13:33 UTC, saigiridhar21 commented on auto-generated-sdk/FactSet.AnalyticsAPI.Engines.sln
>  Microsoft Visual Studio Solution File, Format Version 12.00
Can you revert the sln file changes?

2022-01-10 13:33 UTC, saigiridhar21 commented on examples/FactSet.AnalyticsAPI.Engines.Example/Examples/SPAREngineMultipleUnitExample.cs
> +        private const string Frequency = "Monthly";
Can you please use SPAR prefix similar to other variables?

2022-01-11 05:41 UTC, saigiridhar21 approved these changes

2022-01-11 05:41 UTC, Ramanth approved these changes

2022-01-11 07:13 UTC, merged